// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlSfF5qVzFgMhZPK2aqG2DQsXD-AK6H0',
    appId: '1:640748170554:web:5c94fbc7324c6439cbf403',
    messagingSenderId: '640748170554',
    projectId: 'login-aaabd',
    authDomain: 'login-aaabd.firebaseapp.com',
    storageBucket: 'login-aaabd.appspot.com',
    measurementId: 'G-WZV867ME8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEEZuj_yPCFJ7PfqEWjXiczvU_xk-hZVw',
    appId: '1:640748170554:android:43a7ee4af474073ccbf403',
    messagingSenderId: '640748170554',
    projectId: 'login-aaabd',
    storageBucket: 'login-aaabd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGXEv9zi5V5UDjMDzieereNYODJoeTYIw',
    appId: '1:640748170554:ios:95b3ef71c231fcc5cbf403',
    messagingSenderId: '640748170554',
    projectId: 'login-aaabd',
    storageBucket: 'login-aaabd.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGXEv9zi5V5UDjMDzieereNYODJoeTYIw',
    appId: '1:640748170554:ios:f8e9494e65723712cbf403',
    messagingSenderId: '640748170554',
    projectId: 'login-aaabd',
    storageBucket: 'login-aaabd.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
